server:
  port: 9090

spring:
  application:
    name: fom-api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: fom-order-service
          uri: lb://fom-order-service
          predicates:
            - Path=/food-o-meter-order-service/v1/**
        - id: fom-item-service
          uri: lb://fom-item-service
          predicates:
            - Path=/food-o-meter-item-service/v1/**
        - id: fom-user-service
          uri: lb://fom-user-service
          predicates:
            - Path=/food-o-meter-user-service/v1/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders:
              - content-type
              - accept
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://netflix:eureka@localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true
