server:
  port: 0

spring:
  application:
    name: fom-item-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://netflix:eureka@localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true

logging:
  level:
    root: info