package com.springmicro.foodometer.constants;

public enum FoodOrderEvent {
    CANCEL_ORDER, VALIDATE_ORDER, VALIDATED, VALIDATION_FAILED, PREPARE_FOOD, FOOD_PREPARED, READY_FOR_PICKUP,
    ORDER_PICKED_UP, ORDER_DELIVERY
}
