server:
  port: 9090

spring:
  application:
    name: fom-api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: fom-order-service
          uri: http://localhost:8081/
          predicates:
            - Path=/food-o-meter-order-service/v1/**
        - id: fom-item-service
          uri: http://localhost:8082/
          predicates:
            - Path=/food-o-meter-item-service/v1/**

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://netflix:eureka@localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true

logging:
  level:
    guru:
      springframework: debug