server:
  port: 8081

spring:
  application:
    name: fom-order-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
  cloud:
    discovery:
      enabled: true
  artemis:
    user: artemis
    password: admin

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://netflix:eureka@localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true

logging:
  level:
    root: warn
    org:
      springframework:
        web: debug