server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: fom-service-discovery
  security:
    user:
      name: netflix
      password: eureka
